### ISSUE TITLE
Unhandled exception when running example app

### ISSUE THREAD

**Issue by Tuke82** [sofiyevsr/flutter_remoter#8]
Example project `examples/query` throws unhandled exception when any detail view is opened.
```
E/flutter (26289): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: type 'RemoterData<SingleProduct>' is not a subtype of type 'RemoterData<List<SingleProduct>>' in type cast
E/flutter (26289): #0      CastStreamSubscription._onData (dart:_internal/async_cast.dart:72:25)
E/flutter (26289): #1      _RootZone.runUnaryGuarded (dart:async/zone.dart:1586:10)
E/flutter (26289): #2      _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:339:11)
E/flutter (26289): #3      _DelayedData.perform (dart:async/stream_impl.dart:515:14)
E/flutter (26289): #4      _PendingEvents.handleNext (dart:async/stream_impl.dart:620:11)
E/flutter (26289): #5      _PendingEvents.schedule.<anonymous closure> (dart:async/stream_impl.dart:591:7)
E/flutter (26289): #6      _microtaskLoop (dart:async/schedule_microtask.dart:40:21)
E/flutter (26289): #7      _startMicrotaskLoop (dart:async/schedule_microtask.dart:49:5)
```

Tested with Pixel 5 emulator and iPhone 14 Pro simulator running on M1 Macbook.

Flutter version:
```
Flutter 3.3.8 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 52b3dc25f6 (2 weeks ago) • 2022-11-09 12:09:26 +0800
Engine • revision 857bd6b74c
Tools • Dart 2.18.4 • DevTools 2.15.0
```

**Comment by sofiyevsr** [comment]
Thanks for reporting, fixed
